### ISSUE TITLE
[Add a ride] "Kyiv-Odessa" route isn't build

### ISSUE THREAD

**Issue by VikaUrzan** [ita-social-projects/SoftServeCar-Back-End#686] opened 2021-09-07 10:08 UTC
**Environment:** Xiaomi MiA1, Android 9
**Reproducible:** sometimes
**Build found:** v1.0.303

**Preconditions**
"Car" is opened

**Steps to reproduce**
1. Go to 'Add to ride'
2. Click on 'From' field.
3. Enter 'Kyiv'.
4. Click on 'To' field.
5. Enter 'Odessa'.
6. Double click 'Confirm' button.

**Actual result**

1. Route isn't built.
2. App show error message.

**Expected result**
Route is built

"Bug" ("bug"), Priority ("pri: medium")

https://user-images.githubusercontent.com/67322591/132326693-8d574464-5faa-4a46-a048-da5715b8603b.mp4

**Comment by vladzavorotny** [comment] 2021-09-13 06:52
Cannot reproduce
Some of the routes GoogleMaps cannot build

**Comment by VikaUrzan** [comment] 2021-09-20 07:07
Bug reproduce if quickly double tap "Confirm" button

**Comment by vladzavorotny** [comment] 2021-09-27 09:18
won't fix

**Closed as completed by vladzavorotny** 2021-09-27 09:18 UTC
Labels: bug, pri:medium
